#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug  5 17:39:46 2019

@author: Ashutosh Shukla
https://elitedatascience.com/python-seaborn-tutorial
https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html
https://www.kaggle.com/kanncaa1/seaborn-tutorial-for-beginners  
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from subprocess import check_output
print(check_output(["ls", "../datasets"]).decode("utf8"))

medianHouseHoldIncome = pd.read_csv('../datasets/MedianHouseholdIncome2015.csv', encoding="windows-1252");

percentagePeopleBelowPovertyLevel=pd.read_csv('../datasets/PercentagePeopleBelowPovertyLevel.csv', encoding="windows-1252");

percentageOver25CompletedHighSchool = pd.read_csv('../datasets/PercentOver25CompletedHighSchool.csv', encoding="windows-1252");

shareRaceByCity=pd.read_csv('../datasets/ShareRaceByCity.csv', encoding="windows-1252");

policeKillingsUs=pd.read_csv('../datasets/PoliceKillingsUS.csv', encoding="windows-1252");

## Data visualization for percentagePeopleBelowPovertyLevel
print(percentagePeopleBelowPovertyLevel.info())

percentagePeopleBelowPovertyLevel.poverty_rate.replace(['-'],0.0,inplace=True);
percentagePeopleBelowPovertyLevel.poverty_rate = percentagePeopleBelowPovertyLevel.poverty_rate.astype(float)

area_list= list(percentagePeopleBelowPovertyLevel['Geographic Area'].unique())
area_poverty_ratio=[];

for i in area_list:
    x= percentagePeopleBelowPovertyLevel[percentagePeopleBelowPovertyLevel['Geographic Area']==i]
    area_poverty_rate= sum(x.poverty_rate)/len(x)
    area_poverty_ratio.append(area_poverty_rate );    
    
data= pd.DataFrame({'area_list':area_list,'area_poverty_ratio':area_poverty_ratio});
print(data.head())

#visualisation
#plt.figure(figsize=(15,10))
sns.barplot(x="area_list",y="area_poverty_ratio",data=data)   
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    